apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webappcal
  name: webappcal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webappcal
  template:
    metadata:
      labels:
        app: webappcal
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
      - image: 172.31.44.35:8082/webappcal
        name: webappcal
