apiVersion: v1
kind: Service
metadata:
  labels:
    app: webappcal
  name: webappcal
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webappcal
  type: LoadBalancer