name: "Push repo to aws github codecommit"

# if you want manually trigger this action pls unmark this line
# on: [ workflow_dispatch ]
on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Push to AWS CodeCommit
        env:
          CODECOMMIT_HOST:  ${{ secrets.CODECOMMIT_REPO_HOST }}
          CODECOMMIT_REPO_URL: ${{ secrets.CODECOMMIT_REPO_URL }}
          CODECOMMIT_SSH_CONFIG: ${{ secrets.CODECOMMIT_SSH_CONFIG }}
          CODECOMMIT_SSH_PRIVATE_KEY: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        shell: bash
        run: |
          mkdir ~/.ssh
          echo "$CODECOMMIT_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          echo "$CODECOMMIT_SSH_CONFIG" > ~/.ssh/config && chmod 600 ~/.ssh/config
          ssh-keyscan "$CODECOMMIT_HOST" >> ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
          git remote add codecommit "$CODECOMMIT_REPO_URL"
          git push codecommit ${{ env.BRANCH_NAME }}:${{ env.BRANCH_NAME }} -f
